args <- commandArgs(trailingOnly=TRUE)
root <- normalizePath(".")
source(file.path(root,"scripts/check_public_raw_reads.R"), encoding="UTF-8")
source(file.path(root,"scripts/render_definition_bundle.R"), encoding="UTF-8")
passed <- character()
ok <- function(name, expr) { force(expr); passed <<- c(passed,name) }
reject <- function(name, expr) { value <- tryCatch({force(expr);FALSE}, error=function(e)TRUE); if (!value) stop("Expected rejection: ",name); passed <<- c(passed,name) }
read_code <- c('dt <- read.csv("raw_data.csv", colClasses=c(id="character"))','name_z <- read.csv("raw_codebook.csv")')
ok("KNHANES direct character read",check_public_raw_reads(read_code,"KNHANES"))
reject("KNHANES default numeric coercion",check_public_raw_reads(c('dt <- read.csv("raw_data.csv")',read_code[[2]]),"KNHANES"))
reject("nonidentity colClasses",check_public_raw_reads(c('dt <- read.csv("raw_data.csv", colClasses=c(id="character",sex="character"))',read_code[[2]]),"KNHANES"))
reject("extra fileEncoding",check_public_raw_reads(c('dt <- read.csv("raw_data.csv", colClasses=c(id="character"),fileEncoding="UTF-8")',read_code[[2]]),"KNHANES"))
ok("CHARLS existing simple reads",check_public_raw_reads(c('dt <- read.csv("raw_data.csv")',read_code[[2]]),"CHARLS"))
ok("SHARE existing identity read",check_public_raw_reads(c('dt <- read.csv("raw_data.csv", colClasses=c(mergeid="character"))',read_code[[2]]),"SHARE"))
frame <- data.frame(ID=c("2007_001","2008_001"),id=c("001","001"),year=c(2007L,2008L),sex=c(1L,2L))
ok("render permits same id different year",validate_knhanes_render_inputs(list(frame,frame,frame),c("2007","2008")))
reject("render rejects repeated person-year",validate_knhanes_render_inputs(list(rbind(frame,frame[1,])),c("2007","2008")))
bad <- frame;bad$id <- as.integer(bad$id)
reject("render rejects numeric id",validate_knhanes_render_inputs(list(bad),c("2007","2008")))
bad <- frame;bad$ID[[1]] <- "2007_1"
reject("render checks derived identity",validate_knhanes_render_inputs(list(bad),c("2007","2008")))
reject("render rejects invented year",validate_knhanes_render_inputs(list(frame),c("2006","2007","2008")))
reject("render requires explicit order",validate_knhanes_render_inputs(list(frame),c("2008","2007")))
cat("Synthetic R tests:",length(passed),"passed\n")
