args <- commandArgs(TRUE)
root <- normalizePath(getwd(), winslash="/", mustWork=TRUE)
scripts <- Sys.getenv('DBCODEBOOK_TEST_SCRIPTS', unset=file.path(root,'staged/scripts'))
if (!dir.exists(scripts)) scripts <- file.path(root,'scripts')
render <- readLines(file.path(scripts, 'render_definition_bundle.R'), warn=FALSE, encoding='UTF-8')
invisible(parse(text=render))
invisible(parse(file=file.path(scripts, 'summary_fact_helpers.R')))
invisible(parse(file=file.path(scripts, 'check_public_raw_reads.R')))
start <- grep('  if \\(database == "KLOSA"\\) \\{', render)[1]
end <- grep('  if \\(database == "ELSA" && missing', render)[1] - 1
block <- paste(render[start:end], collapse='\n')
f <- eval(parse(text=paste0('function(data, db_data=data, analysis_data=data, language="ko", cycle_order=paste("Wave",1:10)) {database <- "KLOSA"; ',block,'; list(data=data, db_data=db_data, analysis_data=analysis_data)}')))
d <- data.frame(ID=c('00001_1','00001_10'), Harmonized_id=c('00001','00001'), Wave_id=c('1','10'), sex=c(1,5))
result <- f(d,cycle_order=paste('Wave',1:10))
stopifnot(identical(result$data$ID,d$ID),identical(result$data$Wave_id,d$Wave_id),identical(result$data$Wave,c('Wave 1','Wave 10')),identical(d[['Wave']],NULL))
must_fail <- function(expr) stopifnot(inherits(tryCatch({force(expr);NULL},error=identity),'error'))
must_fail(f(d,language='en',cycle_order=paste('Wave',1:9)))
must_fail(f(d,language=NULL,cycle_order=paste('Wave',1:10)))
subset <- d; subset$Wave_id <- c('9','10')
stopifnot(identical(f(subset,cycle_order=paste('Wave',9:10))$data$Wave,c('Wave 9','Wave 10')))
must_fail(f(d,cycle_order=paste('Wave',c(10,1))))
must_fail(f(d,cycle_order=paste('Wave',c(1,11))))
must_fail(f(d,cycle_order=paste('Wave',c(1,1,10))))
must_fail(f(d,cycle_order=character()))
must_fail(f(rbind(d,d[1,]),cycle_order=paste('Wave',1:10)))
source(file.path(scripts,'summary_fact_helpers.R'))
link <- summary_render_parts(list(list(type='source_link',value='A. Demographics',database='klosa',language='ko')),'#123456')
stopifnot(grepl('/home/klosa/ko/',link,fixed=TRUE))
source(file.path(scripts,'check_public_raw_reads.R'))
lines <- c('dt <- read.csv("raw_data.csv", colClasses=c(ID="character",Harmonized_id="character",Wave_id="character"))', 'name_z <- read.csv("raw_codebook.csv")')
check_public_raw_reads(lines,'KLOSA')
must_fail(check_public_raw_reads(sub('ID="character"','sex="character"',lines,fixed=TRUE),'KLOSA'))
must_fail(check_public_raw_reads(lines,'CHARLS'))
cat('R syntax/projection/negative checks passed; full bundle not executed\n')



bad <- d; bad$Harmonized_id <- c(1,1); must_fail(f(bad))
bad <- d; bad$ID[1] <- ""; must_fail(f(bad))
bad <- d; bad$Wave_id <- c("1","1"); must_fail(f(bad))

source(file.path(scripts,"render_definition_bundle.R"), encoding="UTF-8")
error <- tryCatch(render_definition_bundle(data=d,db_data=d,analysis_data=d,database="KLOSA",language="ko",cycle_order=paste("Wave",1:10),summary_source=list(path="A. Demographics",language="en")),error=identity)
stopifnot(inherits(error,"error"), grepl("source link language",conditionMessage(error),fixed=TRUE))
